version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    command: >
      bash -c "
        mix deps.get
        cd assets &&
        npm install &&
        cd .. &&
        mix ecto.create &&
        mix ecto.migrate &&
        iex -S mix phx.server
      "
    env_file:
      .env
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
    stdin_open: true
    tty: true
